# Site settings
title: 생각하는 쪽으로 삶은 스며든다.
description: Sony A7M3<br/> Sony A7R4<br/> Cannon 1DX Mark II<br/><br/>Cannon EF 24-70 mm F2.8L II USM<br/>Cannon EF 100 mm F2.8L Macro IS USM<br/>Cannon EF 70-200mm F2.8L IS II USM<br/>Sony FE 24-70 mm F2.8 GM<br/>Sony FE 85mm F1.8
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
